const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVICE_ERROR = 500;
const CREATED = 201;
const OK = 200;
const FORBIDDEN = 403;
const UNAUTHORIZED = 401;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVICE_ERROR,
  CREATED,
  OK,
  FORBIDDEN,
  UNAUTHORIZED,
};
